### ISSUE TITLE
登录页

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#1]
登录页中：

- 最低下的‘我已详细阅读并同意xxx’中选中时，打勾的图标很小很小。也没有做不选中的控制和取消选中的效果
- 按返回按钮报错，理应返回去欢迎页
![image](https://user-images.githubusercontent.com/111094976/234033240-8aa5ccea-ae7f-4831-b879-90ce7eefd3d5.png)
![498582471378187956](https://user-images.githubusercontent.com/111094976/234033306-f1d02822-0523-4ae6-a70c-c45ae856b5a4.png)

**Comment by jeawy** [comment]
119版本fix
