### ISSUE TITLE
#帖子

### ISSUE THREAD

**Issue by Finneywang** [jeawy/fun-app-bug-system#10]
1，返回键太靠边不容易按到，与头像名字一起往右边移动
2，头像尺寸缩小
3，地址的字体缩小，小与名字并调整细一号
![image](https://github.com/jeawy/fun-app-bug-system/assets/122250189/992eb174-7096-40fe-806c-a74397613af7)
![image](https://github.com/jeawy/fun-app-bug-system/assets/122250189/e59d6ac3-7a15-4298-ab05-5083529e0bd2)

**Comment by jeawy** [comment]
119版中测试
