### ISSUE TITLE
#评论

### ISSUE THREAD

**Issue by Finneywang** [jeawy/fun-app-bug-system#11]
请参照figma调整
1，点赞爱心与名字对齐，点赞数放在其下方
2，头像尺寸缩小
3，评论时间字体缩小，放置位置参考figma
4，整体字体缩小
![image](https://github.com/jeawy/fun-app-bug-system/assets/122250189/37f42e37-df0a-4fdd-a763-783c77378abd)
![image](https://github.com/jeawy/fun-app-bug-system/assets/122250189/3d83661a-442a-48d7-8266-d466eeef8ad8)

**Comment by jeawy** [comment]
118版本已更新，我们按照设计图，设计了头像大小，日期字体比原先小了2px，请查看对比，并提出具体的调整数据

**Comment by jeawy** [comment]
119版本：
1，点赞爱心与名字对齐【经过沟通，不需要修改】，点赞数放在其下方【已完成】
2，头像尺寸缩小【已按照设计图将一级评论的头像进行修改，请确认修改效果】
3，评论时间字体缩小，放置位置参考figma【已按照设计图进行修改，请确认修改效果】
4，整体字体缩小【缩小多少px？请根据时间的字体大小：12px，内容字体大小：14px，提出具体的修改意见】
已issue 先关闭，有问题，再重新开
