### ISSUE TITLE
首页-关注列表

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#12]
-帖子的点赞和收藏的按钮默认颜色不对
- 一滑到视频类的帖子，版本会出现问题 
- 点击视频类帖子的more，排版出现问题
- 滑到视频帖子，视频应自动播放
- 点击视频本身，去到视频全屏的页面
![199c434bcc8e31bb7dd35d0792b812b](https://github.com/jeawy/fun-app-bug-system/assets/111094976/f1f17e4c-3b7a-458c-a320-d12f94a23d84)
![c14279e898233d40a580c04f3ab2aa8](https://github.com/jeawy/fun-app-bug-system/assets/111094976/d1c482da-d3f8-40fe-92b4-f490487c4870)

**Comment by jeawy** [comment]
125中验证
