### ISSUE TITLE
用户注册-游客访问

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#16]
bug： 作为游客时，看到‘已关注’状态的用户

bug： 作为游客时，点击发帖，看到提示后，点击‘删除’按钮， 还能够进行图片的选择

bug：作为游客时，我还能在‘聊天’页面中看到信息提醒（点赞 & 收藏， 新粉丝，评论 & @） 

bug： 作为游客时， 我还能够看到关注列表

**Comment by jeawy** [comment]
bug：作为游客时，我还能在‘聊天’页面中看到信息提醒（点赞 & 收藏， 新粉丝，评论 & @）【fixed】

**Comment by jeawy** [comment]
作为游客时， 我还能够看到关注列表【fixed】
作为游客时，点击发帖，看到提示后，点击‘删除’按钮， 还能够进行图片的选择【fixed】
bug： 作为游客时，看到‘已关注’状态的用户【未复现，如果有问题，重新开新的issue】
