### ISSUE TITLE
用户注册

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#17]
手机号限制还没完成：现在任意数字都能进行注册。 限制为澳洲手机号码；验证码麻烦后期加一下

昵称查重： 提示框的文字不显示完全

用户头像： 头像是圆形的框，在相册中选择是正方形的框，按’确定‘之后，应该跳转回’完善个人信息‘页面

**Comment by jeawy** [comment]
“按’确定‘之后，应该跳转回’完善个人信息‘页面”,其实就是跳转到完善个人信息页了，只不过图片上传较慢，上传完成就会跳转，现在加了loading。
除了“头像是圆形的框”之外，其他的在123版本中验证。
