### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#2]
登录输入密码时的‘眼睛’的图标可以改回成设计图中的颜色不
包括在‘忘记密码’中的功能中，输入密码和确认密码的图标也得改回设计图的颜色
![557504951354303390](https://user-images.githubusercontent.com/111094976/234035334-f5a41596-22e6-4b97-91bd-750a1b58318d.jpg)
![66216591919753775](https://user-images.githubusercontent.com/111094976/234035359-0bb14d90-19a1-4741-9784-1c0a338d72da.jpg)

**Comment by jeawy** [comment]
119版本中已修复
