### ISSUE TITLE
帖子列表-关注用户列表

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#21]
bug： 关注用户列表中除了‘more’能点，其他按钮都不能点

优化：滑动到视频帖子自动播放，点击视频， 去到视频的全屏页面

麻烦看一下之前一个关于关注列表的一个issue

**Comment by jeawy** [comment]
bug已经修了。优化的“点击视频， 去到视频的全屏页面”这个已经完成了，但是自动播放还没有，后期提到优化中吧
