### ISSUE TITLE
用户发帖

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#25]
bug： 发帖成功后，跳转到 帖子页面，按后退键会回去到发帖流程的页面里

漏的部分和优化：发帖成功后，应跳转到首页，有发帖成功的提醒，如图下
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/ebe8797f-dabd-4c35-bcbf-53394eb069d1)

漏的部分：我直接发粗口，直接就在开心app里展示了，手动审核和自动审核的流程是不是漏了
![f684a3d5cd65806f3aa532844e6ace5](https://github.com/jeawy/fun-app-bug-system/assets/111094976/583b0cce-e107-4513-a520-b13e5c8fb3b2)

优化：页面排版的优化，麻烦弄成和设计图样式
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/fb4c23af-ac6f-40ab-80b1-9127a65d29e4)

 在编辑文字页面中， 按返回按键，弹出的弹框：

- 优化：按‘存储草稿’的提示不对， 显示‘草稿已保存’，然后返回首页
- bug：按‘取消’，有提示，但是没反应
- bug： 按返回‘编’，没放应

优化： 编辑完视频后，去到文字编辑的页面，视频的显示框截取成和图片的显示框一致大小把

bug：打开地址，没有反应

**Comment by jeawy** [comment]
bug： 发帖成功后，跳转到 帖子页面，按后退键会回去到发帖流程的页面里

漏的部分和优化：发帖成功后，应跳转到首页，有发帖成功的提醒，如图下
【通知已加上126版本中验证】

**Comment by jeawy** [comment]
bug：打开地址，没有反应【服务器迁移后验证，需要google访问权限的】

**Comment by jeawy** [comment]
在编辑文字页面中， 按返回按键，弹出的弹框：

优化：按‘存储草稿’的提示不对， 显示‘草稿已保存’，然后返回首页
bug：按‘取消’，有提示，但是没反应
bug： 按返回‘编’，没放应

【没有复现问题】

**Comment by jeawy** [comment]
漏的部分：我直接发粗口，直接就在开心app里展示了，手动审核和自动审核的流程是不是漏了 【不急，后面加】

**Comment by jeawy** [comment]
其他问题在126版本中验证
