### ISSUE TITLE
系统设置

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#29]
通知设置：需要功能做完才能测试

bug: 隐私设置中的‘允许陌生人查看帖子’ ，设置关闭后，互相关注的人应该是能看到的

漏的部分： 用户反馈应该是给到后台的，后台没有反馈的列表

漏的部分： 用户评分，等我们账号提供后，跳转到商城的下载地址

**Comment by jeawy** [comment]
用户评分已完成

**Comment by jeawy** [comment]
通知的问题，需要等google上架后，才可以做测试，重新开个待办吧。
bug: 隐私设置中的‘允许陌生人查看帖子’ ，设置关闭后，互相关注的人应该是能看到的【122中验证】
漏的部分： 用户反馈应该是给到后台的，后台没有反馈的列表【PC端已更新】
漏的部分： 用户评分，等我们账号提供后，跳转到商城的下载地址【已完成】
