### ISSUE TITLE
首页

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#3]
- 登录后应该跳转到首页
- 在首页，关注，附近的帖子列表中，刷新帖子时，加载的图标不应该在最上面，而是在页眉的下方，页眉应该是固定的
- 单击菜单上的‘home’按钮应该是刷新帖子
- 在帖子列表中点击爱心按钮，应该直接给帖子点赞了
- 进入详情页后，页眉应该固定，页眉的所有图标太大了
![image](https://user-images.githubusercontent.com/111094976/234039633-5043d9f6-d995-45ef-ab70-bc2afd1764a0.png)
![image](https://user-images.githubusercontent.com/111094976/234039721-ed8b3743-ab0b-4578-b874-42b3f3bcafb6.png)
![image](https://user-images.githubusercontent.com/111094976/234039801-3c80b3bb-309a-4fec-ba84-08f44f320430.png)

**Comment by jeawy** [comment]
登录后应该跳转到首页【完成】
在首页，关注，附近的帖子列表中，刷新帖子时，加载的图标不应该在最上面，而是在页眉的下方，页眉应该是固定的【完成】
单击菜单上的‘home’按钮应该是刷新帖子【完成，完善了下：双击刷新，单击不操作】
在帖子列表中点击爱心按钮，应该直接给帖子点赞了【全屏的帖子完成了，非全屏的帖子在详情中点赞】
进入详情页后，页眉应该固定，页眉的所有图标太大了【已调整，有问题再反馈】

125中验证
