### ISSUE TITLE
开心钱包

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#30]
优化： 每隔一个时间点才会弹出这个累计登录时长的提示，
譬如：
浏览2mins时长奖励10
浏览5mins时长奖励20
浏览10mins时长奖励50
现在是一直有一个框在提醒浏览时长
bug：提交申请后，我的开心币就直接为负数了
优化：  + AUD 1这个字体太大了
![25bba06c794e4c149d45b4102fff777](https://github.com/jeawy/fun-app-bug-system/assets/111094976/fe941488-ba97-49c4-96e6-90ac54b00463)
优化：体现弹框下面留空太多了，设计图如下
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/a55462a0-9c45-4fe6-802e-447c50040b85)

**Comment by jeawy** [comment]
![image](https://github.com/jeawy/fun-app-bug-system/assets/20496897/ba01342f-5147-401b-b8ae-3564f5c0d558)

**Comment by jeawy** [comment]
122版本中修改完成
