### ISSUE TITLE
会员标语

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#31]
bug：当我在后台的添加多一个标签后，在我的个人页面没有显示出来

优化：在个人页面中的那个'（Bio）'去掉
标签微调一下，麻烦调成这样子
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/f60f0620-cddd-49d3-b5bc-9d2228ace3cf)

**Comment by jeawy** [comment]
【优化及bug修改】122版本中优化
