### ISSUE TITLE
主菜单的按钮

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#32]
底下的5个键间距调一样；中间的‘发帖’按钮可以调成统一大小，如果要保持间距一致的话

**Comment by jeawy** [comment]
在122版本中修复

**Comment by QuinnZuo** [comment]
122版本的中间这个是不是太小了呀
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/db23a915-d0c1-4a41-944c-52dcf7dd402a)
