### ISSUE TITLE
后台-用户列表

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#33]
漏的地方： 用户的发布的帖子的表格

优化： 禁言中的正常状态应该为‘绿色’图标，永久禁言应该为红色图标

**Comment by jeawy** [comment]
![image](https://github.com/jeawy/fun-app-bug-system/assets/20496897/2e194819-1101-49aa-8f4f-88bf38b1fefb)
PC端的bug，close之后第二天验证
