### ISSUE TITLE
后台-帖子列表

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#36]
优化：帖子的阅读数也可以放在列表吗? 能够对阅读数多和少的帖子进行排序。
优化： 点击左边菜单中的‘帖子内容’可否隐藏，通常都是点击某个帖子进入内容的。假如直接在菜单中按‘帖子内容’，不知道去到哪个帖子的
漏的部分： 审核逻辑是不是漏了。第三方的内容审核应该是没有加上的。应该是用户发帖成功了不会第一时间发布到平台上去的，虽然用户能在自己的帖子列表里看到这个帖子。这个帖子会进入后台通过第三方审核检验出是否有问题；不管是否有问题，都是后台决定这个帖子应不应该投放到平台上面去。

**Comment by jeawy** [comment]
优化1【已经优化了】；
优化2：没有发现帖子内容。
审核：之前沟通的是先系统审核，审核通过即可发布。
