### ISSUE TITLE
后台-广告位的管理

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#39]
漏的部分：广告位规则的设定不清楚在后台什么位置设定，我记得上一版的后台是有的好像
![4db1b51c8d65849efe2da5edf6b3129](https://github.com/jeawy/fun-app-bug-system/assets/111094976/33436b13-e668-4405-9e3c-e69126ac9a88)

**Comment by jeawy** [comment]
广告位的位置不支持手动设定，这个我们之前讨论过，原因是：帖子不断的更新，手动设定之后，帖子更新之后，位置可能就出错了，而且瀑布流的左右列差也可能很大。
