### ISSUE TITLE
探索页面

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#4]
- 搜索框中的放大镜应该靠左
- 在搜索页面按返回后，应回到探索页面的初始页面，现在返回会有个‘取消’的按钮在旁边
- 输入搜索的内容，跳转到结果页面，默认应该是帖子类别
- 在搜索结果的列表里，筛选的过滤器只有在选中‘帖子’分类才会有，详情请看设计图；点击用户是没有过滤器
- 点击过滤器才会出现帖子类型
- 帖子与用户两个按钮分割太开了
-历史搜索里没有存搜话题的记录
-话题列表按浏览数排列
![image](https://user-images.githubusercontent.com/111094976/234041965-f5cb3126-45b0-469c-b706-10b25ad23e1d.png)

**Comment by jeawy** [comment]
"话题列表按浏览数排列"这个浏览量指的是话题搜索中的话题的浏览量还是话题中帖子的总浏览量

**Comment by QuinnZuo** [comment]
话题浏览量；然后进入某话题，这个话题下的列表是按话题下帖子总浏览量排序

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jeawy** [comment]
均已完成

**Comment by jeawy** [comment]
![image](https://github.com/jeawy/fun-app-bug-system/assets/20496897/48e1aef9-083e-4187-91b9-89a837b32de1)
