### ISSUE TITLE
后台- 管理权限

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#41]
漏的部分：设定普通用户为管理员

**Comment by jeawy** [comment]
![image](https://github.com/jeawy/fun-app-bug-system/assets/20496897/741afa8c-df73-4568-bbb5-12450797abb5)
![image](https://github.com/jeawy/fun-app-bug-system/assets/20496897/9a0b327f-0515-4623-ad72-d6e2e7e06f32)
