### ISSUE TITLE
消息中心 

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#48]
bug： ’点赞 & 收藏‘中，点赞或者收藏我的帖子的人是其他用户，应该显示的是其他人的头像和名字。 现在显示的都是我自己收藏或者点赞我自己。 其中有一个帖子load不出来图片
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/96bd1362-205c-4e41-a4b2-9a5afaf26014)

bug： ‘评论 & @’中，跟我交互的人是其他用户，但都是自己评论自己，或者自己@自己。应该显示别人的名字。收藏和点赞都应该在’收藏和点赞‘那个列表中
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/2ed004fc-4e16-4d2f-a04d-d56e539a91ba)

bug: 新的粉丝里没有人，但是消息中心显示1个新粉丝。
![0008607f08ace91de6f25f2c26ca344](https://github.com/jeawy/fun-app-bug-system/assets/111094976/3c2e3de4-426a-4aa9-b949-f3da3bf2190e)
![8f2b68879c261aef2fc537203980a79](https://github.com/jeawy/fun-app-bug-system/assets/111094976/239e6d73-d06a-4349-81b7-202d0a140e19)

头像应该为圆形的

bug： 这些点赞，收藏，评论 或@的信息提醒的数字，应该我点进去就消掉了。现在还是一直显示的。譬如‘点赞 & 收藏’ 的新增数是5， 我点进去退出来后，数字’5‘应该消失的。
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/943c07b7-5fd2-4add-8f36-f1bed9c0e092)

bug： 聊天记录中，点击用户，应该跳转到用户的个人主页，现在是没反应

bug： 分享用户的效果如下图，现在是头像和背景图都load不出来
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/eaa317da-116f-4c86-979d-73aa7ba00da4)
![194539866635f5fbeac5cbad333413c](https://github.com/jeawy/fun-app-bug-system/assets/111094976/1136fc51-2247-413a-a0fc-d25b4c467f84)

bug： 分享的帖子的图在聊天记录load不出来。
![194539866635f5fbeac5cbad333413c](https://github.com/jeawy/fun-app-bug-system/assets/111094976/5fd87add-d70a-458a-b2c3-0a09cdbe0540)

聊天记录中，分享的用户不存在，不确定是bug还是这个账户给注销了
![image](https://github.com/jeawy/fun-app-bug-system/assets/111094976/539948c2-b22b-4bf3-98e4-8e53e5e939c0)

**Comment by jeawy** [comment]
bug: 新的粉丝里没有人，但是消息中心显示1个新粉丝。【这个问题应该是显示有一个新粉丝，点进去也有，如果再次点进去就没有了。】

**Comment by jeawy** [comment]
尽量一个bug一个issue，因为将来reopen或者追溯的时候，好追溯。另外issue太长的时候，滚动条拉上拉下也很麻烦

**Comment by jeawy** [comment]
bug： 聊天记录中，点击用户，应该跳转到用户的个人主页，现在是没反应【未复现】

bug： 分享用户的效果如下图，现在是头像和背景图都load不出来【通常是之前的头像被换了，导致原来消息中的图片load不出来】

**Comment by jeawy** [comment]
bug： ’点赞 & 收藏‘中，点赞或者收藏我的帖子的人是其他用户，应该显示的是其他人的头像和名字。 现在显示的都是我自己收藏或者点赞我自己。 其中有一个帖子load不出来图片
bug： ‘评论 & @’中，跟我交互的人是其他用户，但都是自己评论自己，或者自己@自己。应该显示别人的名字。收藏和点赞都应该在’收藏和点赞‘那个列表中
【图片的bug已经修复了，点赞出现在评论列表中的问题也修复了，历史数据不用管】127中验证

**Comment by jeawy** [comment]
bug： ’点赞 & 收藏‘中，点赞或者收藏我的帖子的人是其他用户，应该显示的是其他人的头像和名字。 现在显示的都是我自己收藏或者点赞我自己。 其中有一个帖子load不出来图片
bug： ‘评论 & @’中，跟我交互的人是其他用户，但都是自己评论自己，或者自己@自己。应该显示别人的名字。收藏和点赞都应该在’收藏和点赞‘那个列表中
【图片的bug已经修复了，点赞出现在评论列表中的问题也修复了，历史数据不用管】127中验证
