### ISSUE TITLE
我的

### ISSUE THREAD

**Issue by QuinnZuo** [jeawy/fun-app-bug-system#6]
- 性别的标签需要补上
- 调一下文字（加粗，对齐什么的）和排版把在页眉部分，相差有点明显
- 草稿里的背景搞错了，参考一下设计图。草稿应该放在灰色的背景里的
- 设置
![image](https://user-images.githubusercontent.com/111094976/234049053-4d6e9b7c-e05c-48d3-8703-bffb66878833.png)
![image](https://user-images.githubusercontent.com/111094976/234049280-36ca730c-7dc9-4963-a267-3cc9358da367.png)
![image](https://user-images.githubusercontent.com/111094976/234049875-d45aca82-e1d3-4942-b702-a1920938f4ba.png)

**Comment by jeawy** [comment]
“调一下文字（加粗，对齐什么的）和排版把在页眉部分，相差有点明显”， 新版本中用户名已经加粗，其他的需要具体说明一下

**Comment by QuinnZuo** [comment]
周二我让设计看吧

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jeawy** [comment]
对照最新的app提修改意见吧，因为这个issue提完之后，我们对app的调整还是比较大的。

**Comment by jeawy** [comment]
125中验证一下吧，有问题再把有问题的单独重开issue
