### ISSUE TITLE
#首页

### ISSUE THREAD

**Issue by Finneywang** [jeawy/fun-app-bug-system#8]
1，#附近的人页面 调整location图标大小，确保与右侧距离数字对齐
![image](https://user-images.githubusercontent.com/122250189/236966173-bbb2f17d-13da-45d2-a059-ec2cfa46ccd7.png)
![image](https://user-images.githubusercontent.com/122250189/236966255-0d9017ba-3603-4e52-ae05-a23c7711a646.png)
2.首页全部页面，调整爱心大小确保与右侧数字对齐
![image](https://user-images.githubusercontent.com/122250189/236966592-76864b38-b598-4e8a-9c8e-d560ea61c55e.png)

**Comment by jeawy** [comment]
119版本之后调整完成
