### ISSUE TITLE
#设计 帖子详情

### ISSUE THREAD

**Issue by Finneywang** [jeawy/fun-app-bug-system#9]
1， 调整图标大小与间距 
2，“+关注”字体条粗并调整颜色 色号 12151B
![image](https://user-images.githubusercontent.com/122250189/236967306-0ddc7bd3-95d6-4393-a6d0-9097ab380c6b.png)

3， 将“x条评论”下的下划线调整至日期与地点的下方
4， 每条评论下的分割下划线缩短 
![image](https://user-images.githubusercontent.com/122250189/236967584-1e58cc3a-8899-49e4-900e-9151ed49d13e.png)
![image](https://user-images.githubusercontent.com/122250189/236968135-f104bbfd-3f8a-4595-9b45-c2fa8918c097.png)

5，缩小点赞爱心尺寸

**Comment by jeawy** [comment]
3， 将“x条评论”下的下划线调整至日期与地点的下方
![image](https://github.com/jeawy/fun-app-bug-system/assets/20496897/667690f1-d79e-4dc0-bb44-576984ad6e48)

**Comment by jeawy** [comment]
除了上一条评论中的内容外，其余在版本118中修复，如果有问题，再重新open
